// Carousel 관련 상수
export const CAROUSEL_CONSTANTS = {
	// Z-Index 레이어
	Z_INDEX: {
		CARD_CONTENT: 1000,
		RECORD_PLAYER_CONTAINER: 10000,
		RECORD_PLAYER: 10001,
		RECORD_BACKGROUND: 1002,
		RECORD_PATTERN: 1003,
		RECORD_LABEL: 1004,
		RECORD_HOLE: 1005,
		RECORD_PAUSE_ICON: 1006,
		PLAY_BUTTON: 1001,
		ACTIVE_CARD: 20,
		INACTIVE_CARD_BASE: 10,
	},

	// 애니메이션 설정
	ANIMATION: {
		CONTENT_DELAY: 400, // ms
		ROTATION_DURATION: 3, // seconds
		FADE_DURATION: 0.5, // seconds
		SCALE_DURATION: 0.3, // seconds
		SPRING_STIFFNESS: 120,
		SPRING_DAMPING: 28,
		SPRING_MASS: 2.5,
		ROTATE_Y_STIFFNESS: 100,
		ROTATE_Y_DAMPING: 25,
		ROTATE_Y_MASS: 4,
	},

	// 위치 및 크기
	POSITION: {
		HIDDEN_OFFSET: 400,
		HIDDEN_SCALE: 0.5,
		HIDDEN_OPACITY: 0,
		ACTIVE_SCALE: 1,
		ACTIVE_OPACITY: 1,
		INACTIVE_SCALE: 0.8,
		BASE_OFFSET_RANGE_2: 200,
		BASE_OFFSET_DEFAULT: 240,
		EDGE_OFFSET_MULTIPLIER: 0.9,
		SCALE_DECREMENT: 0.1,
		OPACITY_BASE: 0.7,
		OPACITY_RANGE: 0.3,
	},

	// 카드 크기
	CARD_SIZE: {
		ACTIVE_WIDTH: 'min(90vw, 350px)',
		ACTIVE_HEIGHT: 'min(90vw, 350px)',
		INACTIVE_WIDTH: 'min(70vw, 300px)',
		INACTIVE_HEIGHT: 'min(70vw, 300px)',
	},

	// 반응형 브레이크포인트
	BREAKPOINTS: {
		MOBILE: 960,
		TABLET: 1200,
		DESKTOP: 1536,
	},
} as const;
